name: Bitbucket to GitHub Migration

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the GitHub repository
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      # Step 2: Clone the Bitbucket repository
      - name: Clone Bitbucket repository
        env:
          BITBUCKET_USERNAME: ${{ secrets.BITBUCKET_USERNAME }}
          BITBUCKET_APP_PASSWORD: ${{ secrets.BITBUCKET_TOKEN }}
        run: |
          # Escape special characters in the username and password
          BITBUCKET_USERNAME_ESCAPED=$(echo "$BITBUCKET_USERNAME" | sed 's/@/%40/g; s/:/%3A/g')
          BITBUCKET_APP_PASSWORD_ESCAPED=$(echo "$BITBUCKET_APP_PASSWORD" | sed 's/@/%40/g; s/:/%3A/g')
          
          # Clone the Bitbucket repository
          git clone "https://$BITBUCKET_USERNAME_ESCAPED:$BITBUCKET_APP_PASSWORD_ESCAPED@bitbucket.org/<BITBUCKET_USERNAME>/<REPO_NAME>.git" bitbucket-repo

      # Step 3: Copy files from Bitbucket repo to GitHub repo
      - name: Copy files to GitHub repository
        run: |
          # Copy all files (including hidden files) except the .git directory
          rsync -av --exclude='.git' bitbucket-repo/ .
          rm -rf bitbucket-repo

      # Step 4: Commit and push changes to GitHub
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated migration from Bitbucket"
          git push origin main
