name: Bitbucket to Github Code Sync

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone the Bitbucket repository
      - name: Checkout Bitbucket Repo
        env:
          BITBUCKET_USERNAME: ${{ secrets.BITBUCKET_USERNAME }}
          BITBUCKET_TOKEN: ${{ secrets.BITBUCKET_TOKEN }}
          BITBUCKET_REPO: ${{ secrets.REPO_NAME }}
        run: |
          echo "Cloning Bitbucket repository..."
          git clone https://$BITBUCKET_USERNAME:$BITBUCKET_TOKEN@bitbucket.org/$BITBUCKET_USERNAME/$BITBUCKET_REPO.git
          echo "Changing to repository directory..."
          ls -la  # List files to verify the directory contents

      # Step 2: Force Push to GitHub
      - name: Force Push to GitHub
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ secrets.MY_GITHUB_USERNAME }}
          GITHUB_REPO: ${{ secrets.MY_GITHUB_REPO }}
          BITBUCKET_REPO: ${{ secrets.REPO_NAME }}
        run: |
          cd $BITBUCKET_REPO
          echo "Adding GitHub remote..."
          git remote add github https://$GITHUB_USERNAME:$MY_GITHUB_TOKEN@github.com/$GITHUB_USERNAME/$GITHUB_REPO.git || true
          echo "Force pushing to GitHub..."
          git push github --all --force
          git push github --tags --force
          echo "Code synced successfully (forced)."

