name: Bitbucket to Github code Sync

on:
  push:
    branches:
      - main  
  workflow_dispatch:  

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Bitbucket Repo
        run: |
          git clone https://$BITBUCKET_USERNAME:$BITBUCKET_TOKEN@bitbucket.org/<bitbucket-username>/<bitbucket-repo>.git
          cd <bitbucket-repo>

      - name: Push to GitHub
        run: |
          git remote add github https://$GITHUB_ACTOR:$MY_GITHUB_TOKEN@github.com/<github-username>/<github-repo>.git
          git push github --all
          git push github --tags

