name: Bitbucket to Github Code Sync

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '*/1 * * * *' # Every minute

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Bitbucket Repo
        env:
          BITBUCKET_USERNAME: ${{ secrets.BITBUCKET_USERNAME }}
          BITBUCKET_TOKEN: ${{ secrets.BITBUCKET_TOKEN }}
          BITBUCKET_REPO: ${{ secrets.REPO_NAME }}
        run: |
          echo "Cloning Bitbucket repository..."
          git clone https://$BITBUCKET_USERNAME:$BITBUCKET_TOKEN@bitbucket.org/$BITBUCKET_USERNAME/$BITBUCKET_REPO.git
          ls -la $BITBUCKET_REPO

      - name: Push to GitHub
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ secrets.MY_GITHUB_USERNAME }}
          GITHUB_REPO: ${{ secrets.MY_GITHUB_REPO }}
          BITBUCKET_REPO: ${{ secrets.REPO_NAME }}
        run: |
          cd $BITBUCKET_REPO
          git remote add github https://$GITHUB_USERNAME:$MY_GITHUB_TOKEN@github.com/$GITHUB_USERNAME/$GITHUB_REPO.git || true
          git push github --all --force
          git push github --tags --force

