name: Bitbucket to Github Code Sync

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '*/1 * * * *' # Every minute

jobs:
  backup_and_migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Bitbucket Repo
        env:
          BITBUCKET_USERNAME: ${{ secrets.BITBUCKET_USERNAME }}
          BITBUCKET_TOKEN: ${{ secrets.BITBUCKET_TOKEN }}
          BITBUCKET_REPO: ${{ secrets.REPO_NAME }}
        run: |
          echo "Cloning Bitbucket repository..."
          git clone https://bitbucket.org/$BITBUCKET_USERNAME/$BITBUCKET_REPO.git
          ls -la $BITBUCKET_REPO
          
      - name: Backup to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          BITBUCKET_REPO: ${{ secrets.REPO_NAME }}
        run: |
          echo "Creating backup archive..."
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          ARCHIVE_NAME="$BITBUCKET_REPO-$TIMESTAMP.tar.gz"
          tar -czf $ARCHIVE_NAME $BITBUCKET_REPO
          echo "Uploading backup to S3..."
          aws s3 cp $ARCHIVE_NAME s3://$S3_BUCKET_NAME/$ARCHIVE_NAME
          echo "Backup uploaded successfully."

      - name: Push to GitHub
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ secrets.MY_GITHUB_USERNAME }}
          GITHUB_REPO: ${{ secrets.MY_GITHUB_REPO }}
          BITBUCKET_REPO: ${{ secrets.REPO_NAME }}
        run: |
          cd $BITBUCKET_REPO
          git remote add github https://$GITHUB_USERNAME:$MY_GITHUB_TOKEN@github.com/$GITHUB_USERNAME/$GITHUB_REPO.git || true
          git push github --all --force
          git push github --tags --force

          echo "Done"
